# Generated by protoc-slimrpc-plugin
# This file is generated from an embedded template. Do not edit directly.

from datetime import timedelta
from typing import Optional

from google.rpc import code_pb2 as code__pb2

import slim_bindings

import google.protobuf.empty_pb2 as google__protobuf__empty_pb2
from a2a.grpc import a2a_pb2 as a2a__pb2


class A2AServiceStub:
    """Client stub for A2AService."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A slim_bindings.Channel.
        """
        self._channel = channel

    async def SendMessage(self, request: a2a__pb2.SendMessageRequest, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None) -> a2a__pb2.SendMessageResponse:
        """Call SendMessage method."""
        response_bytes = await self._channel.call_unary_async(
            "a2a.v1.A2AService",
            "SendMessage",
            a2a__pb2.SendMessageRequest.SerializeToString(request),
            timeout,
            metadata,
        )
        return a2a__pb2.SendMessageResponse.FromString(response_bytes)

    async def SendStreamingMessage(self, request: a2a__pb2.SendMessageRequest, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None):
        """Call SendStreamingMessage method."""
        response_stream = await self._channel.call_unary_stream_async(
            "a2a.v1.A2AService",
            "SendStreamingMessage",
            a2a__pb2.SendMessageRequest.SerializeToString(request),
            timeout,
            metadata,
        )
        while True:
            stream_msg = await response_stream.next_async()
            if stream_msg.is_end():
                break
            if stream_msg.is_error():
                raise stream_msg[0]
            if stream_msg.is_data():
                yield a2a__pb2.StreamResponse.FromString(stream_msg[0])

    async def GetTask(self, request: a2a__pb2.GetTaskRequest, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None) -> a2a__pb2.Task:
        """Call GetTask method."""
        response_bytes = await self._channel.call_unary_async(
            "a2a.v1.A2AService",
            "GetTask",
            a2a__pb2.GetTaskRequest.SerializeToString(request),
            timeout,
            metadata,
        )
        return a2a__pb2.Task.FromString(response_bytes)

    async def CancelTask(self, request: a2a__pb2.CancelTaskRequest, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None) -> a2a__pb2.Task:
        """Call CancelTask method."""
        response_bytes = await self._channel.call_unary_async(
            "a2a.v1.A2AService",
            "CancelTask",
            a2a__pb2.CancelTaskRequest.SerializeToString(request),
            timeout,
            metadata,
        )
        return a2a__pb2.Task.FromString(response_bytes)

    async def TaskSubscription(self, request: a2a__pb2.TaskSubscriptionRequest, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None):
        """Call TaskSubscription method."""
        response_stream = await self._channel.call_unary_stream_async(
            "a2a.v1.A2AService",
            "TaskSubscription",
            a2a__pb2.TaskSubscriptionRequest.SerializeToString(request),
            timeout,
            metadata,
        )
        while True:
            stream_msg = await response_stream.next_async()
            if stream_msg.is_end():
                break
            if stream_msg.is_error():
                raise stream_msg[0]
            if stream_msg.is_data():
                yield a2a__pb2.StreamResponse.FromString(stream_msg[0])

    async def CreateTaskPushNotificationConfig(self, request: a2a__pb2.CreateTaskPushNotificationConfigRequest, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None) -> a2a__pb2.TaskPushNotificationConfig:
        """Call CreateTaskPushNotificationConfig method."""
        response_bytes = await self._channel.call_unary_async(
            "a2a.v1.A2AService",
            "CreateTaskPushNotificationConfig",
            a2a__pb2.CreateTaskPushNotificationConfigRequest.SerializeToString(request),
            timeout,
            metadata,
        )
        return a2a__pb2.TaskPushNotificationConfig.FromString(response_bytes)

    async def GetTaskPushNotificationConfig(self, request: a2a__pb2.GetTaskPushNotificationConfigRequest, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None) -> a2a__pb2.TaskPushNotificationConfig:
        """Call GetTaskPushNotificationConfig method."""
        response_bytes = await self._channel.call_unary_async(
            "a2a.v1.A2AService",
            "GetTaskPushNotificationConfig",
            a2a__pb2.GetTaskPushNotificationConfigRequest.SerializeToString(request),
            timeout,
            metadata,
        )
        return a2a__pb2.TaskPushNotificationConfig.FromString(response_bytes)

    async def ListTaskPushNotificationConfig(self, request: a2a__pb2.ListTaskPushNotificationConfigRequest, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None) -> a2a__pb2.ListTaskPushNotificationConfigResponse:
        """Call ListTaskPushNotificationConfig method."""
        response_bytes = await self._channel.call_unary_async(
            "a2a.v1.A2AService",
            "ListTaskPushNotificationConfig",
            a2a__pb2.ListTaskPushNotificationConfigRequest.SerializeToString(request),
            timeout,
            metadata,
        )
        return a2a__pb2.ListTaskPushNotificationConfigResponse.FromString(response_bytes)

    async def GetAgentCard(self, request: a2a__pb2.GetAgentCardRequest, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None) -> a2a__pb2.AgentCard:
        """Call GetAgentCard method."""
        response_bytes = await self._channel.call_unary_async(
            "a2a.v1.A2AService",
            "GetAgentCard",
            a2a__pb2.GetAgentCardRequest.SerializeToString(request),
            timeout,
            metadata,
        )
        return a2a__pb2.AgentCard.FromString(response_bytes)

    async def DeleteTaskPushNotificationConfig(self, request: a2a__pb2.DeleteTaskPushNotificationConfigRequest, timeout: Optional[timedelta] = None, metadata: Optional[dict[str, str]] = None) -> google__protobuf__empty_pb2.Empty:
        """Call DeleteTaskPushNotificationConfig method."""
        response_bytes = await self._channel.call_unary_async(
            "a2a.v1.A2AService",
            "DeleteTaskPushNotificationConfig",
            a2a__pb2.DeleteTaskPushNotificationConfigRequest.SerializeToString(request),
            timeout,
            metadata,
        )
        return google__protobuf__empty_pb2.Empty.FromString(response_bytes)



class A2AServiceServicer:
    """Server servicer for A2AService. Implement this class to provide your service logic."""

    def SendMessage(self, request, context):
        """Method for SendMessage. Implement your service logic here."""
        raise slim_bindings.RpcError.Rpc(
            code=slim_bindings.RpcCode.UNIMPLEMENTED,
            message="Method not implemented!",
            details=None
        )

    def SendStreamingMessage(self, request, context):
        """Method for SendStreamingMessage. Implement your service logic here."""
        raise slim_bindings.RpcError.Rpc(
            code=slim_bindings.RpcCode.UNIMPLEMENTED,
            message="Method not implemented!",
            details=None
        )

    def GetTask(self, request, context):
        """Method for GetTask. Implement your service logic here."""
        raise slim_bindings.RpcError.Rpc(
            code=slim_bindings.RpcCode.UNIMPLEMENTED,
            message="Method not implemented!",
            details=None
        )

    def CancelTask(self, request, context):
        """Method for CancelTask. Implement your service logic here."""
        raise slim_bindings.RpcError.Rpc(
            code=slim_bindings.RpcCode.UNIMPLEMENTED,
            message="Method not implemented!",
            details=None
        )

    def TaskSubscription(self, request, context):
        """Method for TaskSubscription. Implement your service logic here."""
        raise slim_bindings.RpcError.Rpc(
            code=slim_bindings.RpcCode.UNIMPLEMENTED,
            message="Method not implemented!",
            details=None
        )

    def CreateTaskPushNotificationConfig(self, request, context):
        """Method for CreateTaskPushNotificationConfig. Implement your service logic here."""
        raise slim_bindings.RpcError.Rpc(
            code=slim_bindings.RpcCode.UNIMPLEMENTED,
            message="Method not implemented!",
            details=None
        )

    def GetTaskPushNotificationConfig(self, request, context):
        """Method for GetTaskPushNotificationConfig. Implement your service logic here."""
        raise slim_bindings.RpcError.Rpc(
            code=slim_bindings.RpcCode.UNIMPLEMENTED,
            message="Method not implemented!",
            details=None
        )

    def ListTaskPushNotificationConfig(self, request, context):
        """Method for ListTaskPushNotificationConfig. Implement your service logic here."""
        raise slim_bindings.RpcError.Rpc(
            code=slim_bindings.RpcCode.UNIMPLEMENTED,
            message="Method not implemented!",
            details=None
        )

    def GetAgentCard(self, request, context):
        """Method for GetAgentCard. Implement your service logic here."""
        raise slim_bindings.RpcError.Rpc(
            code=slim_bindings.RpcCode.UNIMPLEMENTED,
            message="Method not implemented!",
            details=None
        )

    def DeleteTaskPushNotificationConfig(self, request, context):
        """Method for DeleteTaskPushNotificationConfig. Implement your service logic here."""
        raise slim_bindings.RpcError.Rpc(
            code=slim_bindings.RpcCode.UNIMPLEMENTED,
            message="Method not implemented!",
            details=None
        )




class _A2AServiceServicer_SendMessage_Handler:
    def __init__(self, servicer):
        self.servicer = servicer

    async def handle(self, request: bytes, context: slim_bindings.Context) -> bytes:
        try:
            request_msg = a2a__pb2.SendMessageRequest.FromString(request)
            response = await self.servicer.SendMessage(request_msg, context)
            return a2a__pb2.SendMessageResponse.SerializeToString(response)
        except slim_bindings.RpcError:
            raise
        except Exception as e:
            raise slim_bindings.RpcError.Rpc(
                code=slim_bindings.RpcCode.INTERNAL,
                message=str(e),
                details=None
            )

class _A2AServiceServicer_SendStreamingMessage_Handler:
    def __init__(self, servicer):
        self.servicer = servicer

    async def handle(self, request: bytes, context: slim_bindings.Context, sink: slim_bindings.ResponseSink):
        try:
            request_msg = a2a__pb2.SendMessageRequest.FromString(request)
            response_iter = self.servicer.SendStreamingMessage(request_msg, context)
            async for response in response_iter:
                await sink.send_async(a2a__pb2.StreamResponse.SerializeToString(response))
            await sink.close_async()
        except slim_bindings.RpcError as e:
            await sink.send_error_async(e)
        except Exception as e:
            rpc_error = slim_bindings.RpcError.Rpc(
                code=slim_bindings.RpcCode.INTERNAL,
                message=str(e),
                details=None
            )
            await sink.send_error_async(rpc_error)

class _A2AServiceServicer_GetTask_Handler:
    def __init__(self, servicer):
        self.servicer = servicer

    async def handle(self, request: bytes, context: slim_bindings.Context) -> bytes:
        try:
            request_msg = a2a__pb2.GetTaskRequest.FromString(request)
            response = await self.servicer.GetTask(request_msg, context)
            return a2a__pb2.Task.SerializeToString(response)
        except slim_bindings.RpcError:
            raise
        except Exception as e:
            raise slim_bindings.RpcError.Rpc(
                code=slim_bindings.RpcCode.INTERNAL,
                message=str(e),
                details=None
            )

class _A2AServiceServicer_CancelTask_Handler:
    def __init__(self, servicer):
        self.servicer = servicer

    async def handle(self, request: bytes, context: slim_bindings.Context) -> bytes:
        try:
            request_msg = a2a__pb2.CancelTaskRequest.FromString(request)
            response = await self.servicer.CancelTask(request_msg, context)
            return a2a__pb2.Task.SerializeToString(response)
        except slim_bindings.RpcError:
            raise
        except Exception as e:
            raise slim_bindings.RpcError.Rpc(
                code=slim_bindings.RpcCode.INTERNAL,
                message=str(e),
                details=None
            )

class _A2AServiceServicer_TaskSubscription_Handler:
    def __init__(self, servicer):
        self.servicer = servicer

    async def handle(self, request: bytes, context: slim_bindings.Context, sink: slim_bindings.ResponseSink):
        try:
            request_msg = a2a__pb2.TaskSubscriptionRequest.FromString(request)
            response_iter = self.servicer.TaskSubscription(request_msg, context)
            async for response in response_iter:
                await sink.send_async(a2a__pb2.StreamResponse.SerializeToString(response))
            await sink.close_async()
        except slim_bindings.RpcError as e:
            await sink.send_error_async(e)
        except Exception as e:
            rpc_error = slim_bindings.RpcError.Rpc(
                code=slim_bindings.RpcCode.INTERNAL,
                message=str(e),
                details=None
            )
            await sink.send_error_async(rpc_error)

class _A2AServiceServicer_CreateTaskPushNotificationConfig_Handler:
    def __init__(self, servicer):
        self.servicer = servicer

    async def handle(self, request: bytes, context: slim_bindings.Context) -> bytes:
        try:
            request_msg = a2a__pb2.CreateTaskPushNotificationConfigRequest.FromString(request)
            response = await self.servicer.CreateTaskPushNotificationConfig(request_msg, context)
            return a2a__pb2.TaskPushNotificationConfig.SerializeToString(response)
        except slim_bindings.RpcError:
            raise
        except Exception as e:
            raise slim_bindings.RpcError.Rpc(
                code=slim_bindings.RpcCode.INTERNAL,
                message=str(e),
                details=None
            )

class _A2AServiceServicer_GetTaskPushNotificationConfig_Handler:
    def __init__(self, servicer):
        self.servicer = servicer

    async def handle(self, request: bytes, context: slim_bindings.Context) -> bytes:
        try:
            request_msg = a2a__pb2.GetTaskPushNotificationConfigRequest.FromString(request)
            response = await self.servicer.GetTaskPushNotificationConfig(request_msg, context)
            return a2a__pb2.TaskPushNotificationConfig.SerializeToString(response)
        except slim_bindings.RpcError:
            raise
        except Exception as e:
            raise slim_bindings.RpcError.Rpc(
                code=slim_bindings.RpcCode.INTERNAL,
                message=str(e),
                details=None
            )

class _A2AServiceServicer_ListTaskPushNotificationConfig_Handler:
    def __init__(self, servicer):
        self.servicer = servicer

    async def handle(self, request: bytes, context: slim_bindings.Context) -> bytes:
        try:
            request_msg = a2a__pb2.ListTaskPushNotificationConfigRequest.FromString(request)
            response = await self.servicer.ListTaskPushNotificationConfig(request_msg, context)
            return a2a__pb2.ListTaskPushNotificationConfigResponse.SerializeToString(response)
        except slim_bindings.RpcError:
            raise
        except Exception as e:
            raise slim_bindings.RpcError.Rpc(
                code=slim_bindings.RpcCode.INTERNAL,
                message=str(e),
                details=None
            )

class _A2AServiceServicer_GetAgentCard_Handler:
    def __init__(self, servicer):
        self.servicer = servicer

    async def handle(self, request: bytes, context: slim_bindings.Context) -> bytes:
        try:
            request_msg = a2a__pb2.GetAgentCardRequest.FromString(request)
            response = await self.servicer.GetAgentCard(request_msg, context)
            return a2a__pb2.AgentCard.SerializeToString(response)
        except slim_bindings.RpcError:
            raise
        except Exception as e:
            raise slim_bindings.RpcError.Rpc(
                code=slim_bindings.RpcCode.INTERNAL,
                message=str(e),
                details=None
            )

class _A2AServiceServicer_DeleteTaskPushNotificationConfig_Handler:
    def __init__(self, servicer):
        self.servicer = servicer

    async def handle(self, request: bytes, context: slim_bindings.Context) -> bytes:
        try:
            request_msg = a2a__pb2.DeleteTaskPushNotificationConfigRequest.FromString(request)
            response = await self.servicer.DeleteTaskPushNotificationConfig(request_msg, context)
            return google__protobuf__empty_pb2.Empty.SerializeToString(response)
        except slim_bindings.RpcError:
            raise
        except Exception as e:
            raise slim_bindings.RpcError.Rpc(
                code=slim_bindings.RpcCode.INTERNAL,
                message=str(e),
                details=None
            )


def add_A2AServiceServicer_to_server(servicer, server: slim_bindings.Server):
    server.register_unary_unary(
        service_name="a2a.v1.A2AService",
        method_name="SendMessage",
        handler=_A2AServiceServicer_SendMessage_Handler(servicer),
    )
    server.register_unary_stream(
        service_name="a2a.v1.A2AService",
        method_name="SendStreamingMessage",
        handler=_A2AServiceServicer_SendStreamingMessage_Handler(servicer),
    )
    server.register_unary_unary(
        service_name="a2a.v1.A2AService",
        method_name="GetTask",
        handler=_A2AServiceServicer_GetTask_Handler(servicer),
    )
    server.register_unary_unary(
        service_name="a2a.v1.A2AService",
        method_name="CancelTask",
        handler=_A2AServiceServicer_CancelTask_Handler(servicer),
    )
    server.register_unary_stream(
        service_name="a2a.v1.A2AService",
        method_name="TaskSubscription",
        handler=_A2AServiceServicer_TaskSubscription_Handler(servicer),
    )
    server.register_unary_unary(
        service_name="a2a.v1.A2AService",
        method_name="CreateTaskPushNotificationConfig",
        handler=_A2AServiceServicer_CreateTaskPushNotificationConfig_Handler(servicer),
    )
    server.register_unary_unary(
        service_name="a2a.v1.A2AService",
        method_name="GetTaskPushNotificationConfig",
        handler=_A2AServiceServicer_GetTaskPushNotificationConfig_Handler(servicer),
    )
    server.register_unary_unary(
        service_name="a2a.v1.A2AService",
        method_name="ListTaskPushNotificationConfig",
        handler=_A2AServiceServicer_ListTaskPushNotificationConfig_Handler(servicer),
    )
    server.register_unary_unary(
        service_name="a2a.v1.A2AService",
        method_name="GetAgentCard",
        handler=_A2AServiceServicer_GetAgentCard_Handler(servicer),
    )
    server.register_unary_unary(
        service_name="a2a.v1.A2AService",
        method_name="DeleteTaskPushNotificationConfig",
        handler=_A2AServiceServicer_DeleteTaskPushNotificationConfig_Handler(servicer),
    )
